# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b594a151cf6b1fe091c3a9b27d7c592b01c11bc3f3d685661b1c3bf0babe7e3501ae42f9e8a11dc14790d24d396654996f31ecc78eefb9837e8b327c9583f624

test:
  secret_key_base: 887732c37cd6337bf85545944da669770ba3c094f189ea044a10cbf205466670bd1f15ad1ae7173ff70f59ec3a38bae036fcb4a29467de9bce5f566ff0caa15e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
